var passwordCapital = "";
var passwordLowercase = "";
var passwordNumeric = "";
var passwordSpecial = "";
var capital = "ABCDEFGHIJKLMNOPQURSTUVWXYZ"
var lower = "abcdefghijklmnopqrstuvwxyz"
var numeric = "numeric"
var special = "!@#$%^&*()_+-=[]{},./?";
var passString = "";
var passResult = "";
